steps:
  - label: ":julia: Julia: {{matrix.julia}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
    matrix:
      setup:
        julia:
          - "1"
          - "1.6"
          - "nightly"
      adjustments:
        - with:
            julia: "1.6"
          soft_fail: true
        - with:
            julia: "nightly"
          soft_fail: true

env:
  SECRET_CODECOV_TOKEN: "TTwLG9F33tgVgZHK68A3ReRNBt0sWOMAOlPv4kwqwlbWumO6dmz5Narsc889M89nkGFF18d4N/uDWlrm6yIvBX8KSv84vtDOmV5h4d1r6TDVTumibJsFUnTLUkMfbSxw/Bk/q9DKwkYzb1MsNYFJ+zvx9WHnTBd1TiCOLYIRoqxH3aiipe2Auv1sLHJXsxfOvLyrqmcZC+h9OHbVhvFKgrlXbDqONNhWEX4tkzplhIddi60GwFv9xQe7sXpNNmI3Dz/s7BI5XzOxQwKziWOhfsXHreuyby8/Jl/ncpytQkSYRwOw0u8EKNIzeGTCDhfV1EfeuyCq6BfzwSxSFoe8Dw==;U2FsdGVkX1/amMWov97QY23CDLskhDds8btz5Rh9tunCe2Ky8oocTu/5cOy13GjRfAFlQapr78KQrX67dJm/0g=="
